server:
  host: "0.0.0.0"
  port: 8001


postgres:
  host: "postgres"
  port: 5432
  user: "postgres"
  dbname: "postgres"
  password: "postgres"
  sslmode: "disable"

worker:
  external_api: "https://latest.currency-api.pages.dev/v1/currencies/rub.json"
  fetching_on_start: "True"
  runtime_hour: 10
  runtime_minute: 0

