services:

  currency:
    build:
      context: ./services/currency
      dockerfile: Dockerfile
    container_name: currency-service
    ports:
      - "8001:8001"
    depends_on:
      - postgres
      - auth-generator

  gateway:
    build:
      context: ./services/gateway
      dockerfile: Dockerfile
    container_name: gateway-service
    ports:
      - "8000:8000"
    depends_on:
      - currency

  auth-generator:
    image: andrianovartemii/gm-test-task-auth-generator:amd
    ports:
      - "8082:8080"
    environment:
      AUTH_TOKEN_LIFETIME: 100
    platform: linux/arm64/v8

  postgres:
    hostname: db
    container_name: db
    image: "postgres:12"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: { }