services:
  auth-generator:
    image: andrianovartemii/gm-test-task-auth-generator:amd
    ports:
      - "8082:8080"
    environment:
      AUTH_TOKEN_LIFETIME: 100
    platform: linux/arm64/v8

  postgres:
    hostname: db
    container_name: db
    image: "postgres:12"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: { }